config/routes.rb
Citivine::Application.routes.draw do
	  get "index/index"
	  root :to => "index#index"
	  #match for for webrick subdirectory
	  match '/citivine' => 'index#index'
	  #Search
	  match '/item(/:item)' => 'index#index', :as => :index_item
	  #get feeds (by type, subtype (channels), id (channels))
	  match 'list/:type(/:subtype)(/id/:id)(/page/:page)(/load/:load)' => 'feeds#list', :as => :list
	  #Search
	  match 'search(/:request)(/:type)(/:page)' => 'feeds#search', :as => :search
	  #list feeds by tag id
	  match 'tag/:tag(/page/:page)(/load/:load)(/count/:size)' => 'feeds#tag', :as => :tag
	  #fetch metas by post
	  match 'post(/cat/:cat)(/:type)/:post' => 'feeds#metas', :as => :metas
	  #fetch more metas by post
	  match 'post(/cat/:cat)(/:type)/:post(/page/:page)' => 'feeds#metas_more', :as => :metas_more
	  #uniq user
	  match 'user/:user(/:username)(/page/:page)(/load/:load)' => 'feeds#user', :as => :user
	  #uniq vine uniq post / video
	  match 'vine/:username/:post' => 'feeds#post', :as => :post
	  #test route
	  match 'test/test' => 'feeds#test', :as => :test
	  #Set number of items per page
	  match 'count/:size' => 'index#change_session_size', :as => :change_session_size
	  #Set autoload
	  match 'autoload/:autoload' => 'index#change_session_autoload', :as => :change_session_autoload
	  #Set autoplay
	  match 'autoplay/:autoplay' => 'index#change_session_autoplay', :as => :change_session_autoplay
	  #Set volume
	  match 'volume/:volume' => 'index#change_session_volume', :as => :change_session_volume
	  #About page
	  match 'whatsnew' => 'index#whatsnew', :as => :whatsnew
	  #About page
	  match 'about' => 'index#about', :as => :about
	  #Contact page
	  match 'contact' => 'index#contact', :as => :contact, :via => :get
	  match 'contact' => 'index#contact_send', :as => :contact_send, :via => :post
end

app/controllers/feeds_controller.rb
require 'json'
require 'curb'

class FeedsController < ApplicationController

  protect_from_forgery
  include ApplicationHelper
  before_filter :init_params

  def initialize
    @@c = curl_init
    @@page = Citivine::Application::config.vine_default_page
    @@size = Citivine::Application::config.vine_default_count_items
    super
  end

  def init_params
    if(params[:page])
      @@page = params[:page]
    end
  end

  def list

    base_url = Citivine::Application::config.vine_api_base_url+'timelines/'+params[:type]

    #Channel ID
    if(params[:id])
      base_url += '/'+params[:id].to_s
    end

    #Channel type (recent or popular)
    if(params[:subtype])
      base_url += '/'+params[:subtype]
    end

    #Autoload
    if(params[:load])
      page = params[:load]
    else
      page = @@page
    end

    [base_url+'?page='+page+'&size='+session[:size]].map do |url|
      @@c.url = url
      @@c.perform
      @feeds = ActiveSupport::JSON.decode(@@c.body_str)
    end

    if(params[:load])
        render :partial => 'partials/feed_items', :locals => {:feeds => @feeds}, :layout => false, formats: :html
    end
    
  end

  def post

    userId = nil;
    base_url = Citivine::Application::config.vine_api_base_url+'timelines/posts/'+params[:post]
    [base_url].map do |url|
      @@c.url = url
      @@c.perform
      @post = ActiveSupport::JSON.decode(@@c.body_str)
      @post["data"]["records"].each.with_index do |post, index|
        userId = post["userId"]
      end
    end

    [Citivine::Application::config.vine_api_base_url+'timelines/users/'+userId.to_s].map do |url|
      @@c.url = url
      @@c.perform
      @feeds = ActiveSupport::JSON.decode(@@c.body_str)
    end

    @comments = metas(:post => params[:post], :type => "comments")
    @likes = metas(:post => params[:post], :type => "likes")

    #popup
    if request.referer != nil && URI(request.referer).path != '/'
      render :partial => "partials/post_popup", :layout => false, formats: :html
    end

  end

  def test

    ['https://api.vineapp.com/timelines/venues/1010405498111336448'].map do |url|
      @@c.url = url
      @@c.perform
      @test = ActiveSupport::JSON.decode(@@c.body_str)
    end

  end

  def channels

    base_url = Citivine::Application::config.vine_api_base_url+'timelines/'+params[:type]+'/'+params[:id]+'/'+params[:id]+'?page='+@@page+'&size='+session[:size]
    [base_url].map do |url|
      @@c.url = url
      @@c.perform
      @feeds = ActiveSupport::JSON.decode(@@c.body_str)
    end

  end

  def metas params = {}

    if(params[:cat])
      cat = 'timelines/users/'
    else
      cat = 'posts/'
    end

    metas = Array.new;

    base_url = Citivine::Application::config.vine_api_base_url+cat+params[:post]+'/'+params[:type]+'?page='+@@page+'&size='+@@size.to_s
    [base_url].map do |url|
      @@c.url = url
      @@c.perform
      metas = ActiveSupport::JSON.decode(@@c.body_str)
    end

    return metas
    render nothing: true

  end

  def metas_more

    metas = Array.new;

    base_url = Citivine::Application::config.vine_api_base_url+'posts/'+params[:post]+'/'+params[:type]+'?page='+params[:page]+'&size='+@@size.to_s;
    [base_url].map do |url|
      @@c.url = url
      @@c.perform
      metas = ActiveSupport::JSON.decode(@@c.body_str)
    end

    render :partial => "partials/"+params[:type]+"_items", :locals => {:metas => metas, :post => params[:post]}, :layout => false, formats: :html

  end

  def search

    users = nil;
    tags = nil;

    base_url = Citivine::Application::config.vine_api_base_url+'users/search/'+URI.escape(params[:request])+'?page='+@@page+'&size='+session[:size];
    [base_url].map do |url|
      @@c.url = url
      @@c.perform
      users = ActiveSupport::JSON.decode(@@c.body_str)
    end

    if(params[:type] && params[:type] == 'users')
      render :partial => "partials/search_users", :locals => {:users => users}, :layout => false, formats: :html
    else
      @feeds = users;
    end

    base_url = Citivine::Application::config.vine_api_base_url+'tags/search/'+URI.escape(params[:request])+'?page='+@@page+'&size='+session[:size];
    [base_url].map do |url|
      @@c.url = url
      @@c.perform
      tags = ActiveSupport::JSON.decode(@@c.body_str)
    end

    if(params[:type] && params[:type] == 'tags')
      render :partial => "partials/search_tags", :locals => {:tags => tags}, :layout => false, formats: :html
    else
      @tags = tags;
    end

  end

  def tag
    
    auth
    c = curl_init

    page = Citivine::Application::config.vine_default_page;

    #Autoload
    if(params[:load])
      page = params[:load]
    else
      page = @@page
    end

    [Citivine::Application::config.vine_api_base_url+'timelines/tags/'+params[:tag]+'?page='+page+'&size='+session[:size]].map do |url|
      c.url = url
      c.perform
      @feeds = ActiveSupport::JSON.decode(c.body_str)
    end

    if(params[:load])
      render :partial => 'partials/feed_items', :locals => {:feeds => @feeds}, :layout => false, formats: :html
    else
      render :template => 'feeds/list'
    end
    
  end

  def user

    if(params[:load])
      page = params[:load]
    else
      page = @@page
    end
    
    [Citivine::Application::config.vine_api_base_url+'users/profiles/'+params[:user]].map do |url|
      @@c.url = url
      @@c.perform
      user = ActiveSupport::JSON.decode(@@c.body_str)
      @user = user["data"]
    end

    [Citivine::Application::config.vine_api_base_url+'timelines/users/'+params[:user]+'?page='+page+'&size='+session[:size]].map do |url|
      @@c.url = url
      @@c.perform
      @feeds = ActiveSupport::JSON.decode(@@c.body_str)
    end

    if(params[:load])
      render :partial => 'partials/feed_items', :locals => {:feeds => @feeds}, :layout => false, formats: :html;
    end

  end

end

app/helpers/feed_helper.rb
require 'curb'

module FeedHelper

	def check_from_exists(location)
		if location != nil && location.to_s.length > 0
			true
		else 
			false;
		end
	end

	def check_description_exists(description)
		if description.length > 0 
			true 
		else 
			false;
		end
	end

	def format_large_number(number)
		number_to_human(number.to_i, 
			:precision => 2,
			:signficant => false,
			:units => {
				:unit => '',
				:thousand => 'k', 
				:million => 'm',
				:billion => 'b'
			},
			:format => '%n%u'
		)
	end

 	def auto_link_twitter(txt, options = {:target => "_blank"})
	    txt.scan(/(^|\W|\s+)(#|@)(\w{1,25})/).each do |match|
	  		if match[1] == "#"
		        txt.gsub!(/##{match.last}/, link_to("##{match.last}", "//twitter.com/search/?q=##{match.last}", options))
	    	elsif match[1] == "@"
	          	txt.gsub!(/@#{match.last}/, link_to("@#{match.last}", "//twitter.com/#{match.last}", options))
	      	end
		end
    	txt
  	end

  	def auto_tag_vine(txt, options = {})
	    txt.scan(/(^|\W|\s+)(#|@)(\w{1,25})/).each do |match|
	  		if match[1] == "#"
		        txt.gsub!(/##{match.last}/, link_to("##{match.last}", tag_path(:tag => "#{match.last}"), options))
	      	end
		end
    	txt
  	end

  	def format_date(date)
  		diff_to_now = (Time.now - date.to_time).to_f
  		if diff_to_now/60 < 1
			gap = diff_to_now.to_i.to_s
			gap += (diff_to_now.to_i/60 > 1) ? ' seconds' : ' seconds'
  		elsif diff_to_now/60 > 1 && diff_to_now/3600 < 1
  			gap = (diff_to_now.to_i/60).to_s
  			gap += (diff_to_now.to_i/60 > 1) ? ' minutes' : ' minute'
  		elsif diff_to_now/3600 > 1 && diff_to_now/86400 < 1
  			gap = (diff_to_now.to_i/3600).to_s
  			gap += (diff_to_now.to_i/3600 > 1) ? ' hours' : ' hour'
		else
			gap = (diff_to_now.to_i/86400).to_s
			gap += (diff_to_now.to_i/86400 > 1) ? ' days' : ' day'
		end
  		gap
  	end

end

app/views/feeds/list.html.erb
<%= render :partial => "partials/metas", :locals => { :params => params } %>
<% if params[:subtype] %>
	<div id="channels_tabs">
		<ul class="nav nav-tabs">
			<% active_class = params[:subtype] == "recent" ? 'active' : '' %>
	        <li class="<%= active_class %>">
	        	<%= link_to "Recent", list_path(:type => :channels, :id => params[:id], :subtype => "recent") %>
	        </li>
			<% active_class = params[:subtype] == "popular" ? 'active' : '' %>
	        <li class="<%= active_class %>">
	        	<%= link_to "Popular", list_path(:type => :channels, :id => params[:id], :subtype => "popular") %>
	        </li>
      	</ul>
	</div>
<% end %>
<% if @feeds["success"] != false && @feeds["data"]["records"].count > 0 %>
	<% if(session[:autoload] == '0') %>
		<%= render :partial => "partials/pagination", :locals => { :previous_page => @feeds["data"]["previousPage"], :next_page => @feeds["data"]["nextPage"] } %>
		<hr/>
	<% end %>
	<ul class="feeds_list">
		<% if @feeds["success"] != false %>
			<%= render :partial => 'partials/feed_items', :locals => {:feeds => @feeds} %>
		<% else %>
			<%= render :partial => "partials/error" %>
		<% end %>
	</ul>
	<% if(session[:autoload] == '0') %>
		<hr/>
		<%= render :partial => "partials/pagination", :locals => { :previous_page => @feeds["data"]["previousPage"], :next_page => @feeds["data"]["nextPage"] } %>
	<% else %>
		<script type="text/javascript">
			var next_page = <%= @feeds["data"]["nextPage"] %>;
		</script>
	<% end %>
<% else %>
	No vines found
<% end %>

app/views/feeds/post.html.erb
<%= render :partial => "partials/metas", :locals => { :params => params } %>
<% @post["data"]["records"].each.with_index do |post, index| %>
	<div class="clearfix">
		<div id="post_cont" class="left post_uniq">
			<h2>
				<%= auto_tag_vine(post["description"]).html_safe %>	
			</h2>
			<p>
				<% if check_from_exists(post["location"]) %>
					<i>from <%= post["location"] %>,</i>
				<% end %>
				<i><%= format_date(post["created"]) %> ago</i>
			</p>
			<% volume_class = session[:volume] == '0' ? 'off' : 'on' %>
			<a href="#" class="mute-button <%= volume_class %>"></a>
			<video id="video_<%= post["postId"] %>" class="video-js" poster="<%= post["thumbnailUrl"] %>" loop="" preload="false">
				<source src="<%= post["videoUrl"] %>" type="video/mp4">
			</video>
			<div class="video_cont_infos">
				
			</div>
		</div>
		<div id="metas_cont" class="right">
			<div class="well user_infos">
				<%= link_to user_path(:user => post["userId"], :username => post["username"]), :class => "username" do %>
					<%= image_tag "#{post["avatarUrl"]}", {alt:post["username"], :height => 100, :width => 100, :class => "left user_avatar"} %>
				<% end %>
				<h3 class="left">
					<%= link_to post["username"], user_path(:user => post["userId"], :username => post["username"]), :class => "username" %>
				</h3>
				<span class="left">
					<%= @feeds["data"]["count"] %> vine<%= @feeds["data"]["count"] == 1 ? '' : 's' %>
				</span>
				<div class="clear"></div>
				<div class="user_posts">
					<% if @feeds["data"]["count"] > 1 %>
						<h3><%= post["username"] %>'s last vines:</h3>
					<% end %>
					<% @feeds["data"]["records"].each.with_index do |feed, index| %>
						<% if feed["postId"] && feed["postId"] != post["postId"] %>
							<%= link_to post_path(:username => feed["username"], :userid => feed["userId"], :post => feed["postId"]) do %>
								<%= image_tag "#{feed["thumbnailUrl"]}", {alt:feed["postId"], :height => 90, :width => 90} %>
							<% end %>
						<% end %>
					<% end %>
				</div>
			</div>
			<ul class="nav nav-tabs">
				<li class="active share">
					<%= link_to "Infos", '' %>
				</li>
		        <% if @comments["data"]["count"].to_i > 0 %>
			        <li class="comments">
			        	<%= link_to format_large_number(@comments["data"]["count"])+" Comments", '' %>
			        </li>
		        <% end %>
		        <% if @likes["data"]["count"].to_i > 0 %>
			        <li class="likes">
			        	<%= link_to format_large_number(@likes["data"]["count"])+" Likes", '' %>
			        </li>
		        <% end %>
	      	</ul>
	      	<ul id="share" class="metas">
	      		<% twitter_href = "https://twitter.com/share?url="+post["shareUrl"]+"&amp;text="+post["description"] %>
	      		<a target="_blank" onclick="return !window.open(this.href, 'Twitter', 'width=700,height=400')" href="<%= twitter_href %>">
	      			<i class="icon-share icon-twitter"></i>
	    		</a>
      			<a target="_blank" onclick="return !window.open(this.href, 'Facebook', 'width=700,height=400')" href="https://www.facebook.com/sharer/sharer.php?u=<%= post["shareUrl"] %>">
	      			<i class="icon-share icon-facebook"></i>
	    		</a>
	    		<div id="tags">
	    			<% if post["entities"].length > 0 %>
						<h3>Tags:</h3>
					<% end %>
	    			<% post["entities"].each.with_index do |entity, index| %>
						<% if entity["type"] == "tag" %>
							<% active = params[:tag] && params[:tag] == entity["title"] ? 'current' : '' %>
							<%= link_to entity["title"], tag_path(:tag => entity["title"]), :class => "tag btn btn-small "+ active %>
						<% end %>
					<% end %>
				</div>
			</ul>
			<% if @comments["data"]["count"].to_i > 0 %>
				<ul id="comments" class="metas">
					<%= render :partial => 'partials/comments_items', :locals => {:metas => @comments, :post => params[:post]} %>
				</ul>
			<% end %>
			<% if @likes["data"]["count"].to_i > 0 %>
				<ul id="likes" class="metas clearfix likes_list">
					<%= render :partial => 'partials/likes_items', :locals => {:metas => @likes, :post => params[:post]} %>
				</ul>
			<% end %>
		</div>
	</div>
<% end %>

app/views/feeds/search.html.erb
<%= render :partial => "partials/metas", :locals => { :params => params } %>
<%= form_tag({:controller => "feeds", :action => "search"}, :method => "get", :class => "fullsize-form") do |f| %>
	<%= text_field_tag :request, params[:request], placeholder: "Search people or tag!" %>
	<button type="submit" class="btn">Search</button>
<% end %>
<% if(@feeds["data"]["count"] == 0 && @tags["data"].length == 0) %>
	<h3>Sorry, no tags or users matching "<%= params[:request] %>"</h3>
<% else %>
	<% if(@tags["data"].length > 0) %>
		<h3><%= @tags["data"]["count"] %> tags matching "<%= link_to params[:request], tag_path(:tag => params[:request]) %>" found:</h3>
		<div id="search_results_tags" rel="<%= @tags["data"]["count"] %>">
			<div class="loader"></div>
			<%= render :partial => "partials/search_tags", :locals => {:tags => @tags} %>
			<% if(@tags["data"]["count"] > session[:size].to_i) %>
				<%= link_to search_path(:request => params[:request], :type => "tags"), :rel => '2', :class => "btn btn-primary search_more_content", :data => {'type' => 'tags'} do %>
					<i class="icon-plus"></i>&nbsp;&nbsp;&nbsp;Search more tags
				<% end %>
			<% end %>
		</div>
	<% end %>
	<% if(@feeds["data"]["count"] > 0) %>
		<h3><%= @feeds["data"]["count"] %> users matching "<%= params[:request] %>" found:</h3>
		<ul class="search feeds_list" rel="<%= @feeds["data"]["count"] %>">
			<div class="loader"></div>
			<%= render :partial => "partials/search_users", :locals => {:users => @feeds} %>
			<li class="clear"></li>
			<% if(@feeds["data"]["count"] > session[:size].to_i) %>
				<%= link_to search_path(:request => params[:request], :type => "users"), :rel => '2', :class => "btn btn-primary search_more_content", :data => {'type' => 'users'} do %>
					<i class="icon-plus"></i>&nbsp;&nbsp;&nbsp;Search more users
				<% end %>
			<% end %>
		</ul>
	<% end %>
<% end %>

app/views/feeds/test.html.erb
<%= @test %>

app/views/feeds/user.html.erb
<%= render :partial => "partials/metas", :locals => { :params => params } %>
<ul class="user feeds_list">
	<li>
		<div class="user_resume">
			<div class="user_picture">
				<%= image_tag "#{@user["avatarUrl"]}", {alt:@user["username"], :height => 200, :width => 200} %>
			</div>
			<div class="description_cont left">
				<h2><%= @user["username"] %></h2>
				<% if check_from_exists(@user["location"]) %>
					<i>from <%= @user["location"] %></i></p>
				<% end %>
				<% if @user["description"] %>
					<h4>
						<%= auto_link_twitter(@user["description"]).html_safe %>
					</h4>
				<% end %>
				<p>
					<strong><%= format_large_number(@user["followerCount"]) %></strong> followers / 
					<strong><%= format_large_number(@user["followingCount"]) %></strong> following
				</p>
				<p class="post_metas">
					<strong><%= format_large_number(@user["likeCount"]) %></strong> <i class="icon-heart-empty"></i>
				</p>
			</div>
			<div class="clear"></div>
		</div>
	</li>
</ul>
<% if @feeds["success"] != false && @feeds["data"]["records"].count > 0 %>
	<% if(session[:autoload] == '0') %>
		<%= render :partial => "partials/pagination", :locals => { :previous_page => @feeds["data"]["previousPage"], :next_page => @feeds["data"]["nextPage"] } %>
		<hr/>
	<% end %>
	<ul class="feeds_list">
		<% if(@feeds["data"]["records"]) %>
			<%= render :partial => 'partials/feed_items', :locals => {:feeds => @feeds} %>
		<% else %>
			<%= render :partial => "partials/error" %>
		<% end %>
	</ul>
	<% if(session[:autoload] == '0') %>
		<hr/>
		<%= render :partial => "partials/pagination", :locals => { :previous_page => @feeds["data"]["previousPage"], :next_page => @feeds["data"]["nextPage"] } %>
	<% else %>
		<script type="text/javascript">
			var next_page = <%= @feeds["data"]["nextPage"] %>;
		</script>
	<% end %>
<% else %>
	No vines found
<% end %>