config/routes.rb
Citivine::Application.routes.draw do
	  get "index/index"
	  root :to => "index#index"
	  #match for for webrick subdirectory
	  match '/citivine' => 'index#index'
	  #Search
	  match '/item(/:item)' => 'index#index', :as => :index_item
	  #get feeds (by type, subtype (channels), id (channels))
	  match 'list/:type(/:subtype)(/id/:id)(/page/:page)(/load/:load)' => 'feeds#list', :as => :list
	  #Search
	  match 'search(/:request)(/:type)(/:page)' => 'feeds#search', :as => :search
	  #list feeds by tag id
	  match 'tag/:tag(/page/:page)(/load/:load)(/count/:size)' => 'feeds#tag', :as => :tag
	  #fetch metas by post
	  match 'post(/cat/:cat)(/:type)/:post' => 'feeds#metas', :as => :metas
	  #fetch more metas by post
	  match 'post(/cat/:cat)(/:type)/:post(/page/:page)' => 'feeds#metas_more', :as => :metas_more
	  #uniq user
	  match 'user/:user(/:username)(/page/:page)(/load/:load)' => 'feeds#user', :as => :user
	  #uniq vine uniq post / video
	  match 'vine/:username/:post' => 'feeds#post', :as => :post
	  #test route
	  match 'test/test' => 'feeds#test', :as => :test
	  #Set number of items per page
	  match 'count/:size' => 'index#change_session_size', :as => :change_session_size
	  #Set autoload
	  match 'autoload/:autoload' => 'index#change_session_autoload', :as => :change_session_autoload
	  #Set autoplay
	  match 'autoplay/:autoplay' => 'index#change_session_autoplay', :as => :change_session_autoplay
	  #Set volume
	  match 'volume/:volume' => 'index#change_session_volume', :as => :change_session_volume
	  #About page
	  match 'whatsnew' => 'index#whatsnew', :as => :whatsnew
	  #About page
	  match 'about' => 'index#about', :as => :about
	  #Contact page
	  match 'contact' => 'index#contact', :as => :contact, :via => :get
	  match 'contact' => 'index#contact_send', :as => :contact_send, :via => :post
end

app/views/partials/_comments.html.erb
<div class="white-popup">
	<% if @metas["success"] != false %>
		<ul class="metas_list comments_list">
			<%= render :partial => "partials/"+params[:type]+"_items", :locals => {:metas => @metas} %>	
		</ul>
	<% end %>
	<div class="clear"></div>
	<div class="loader"></div>
</div>

app/views/partials/_comments_items.html.erb
<% metas["data"]["records"].each.with_index do |comment, index| %>
	<li class="clearfix">
		<div class="left">
		<%= link_to user_path(:user => comment["userId"], :username => comment["username"]) do %>
			<%= image_tag "#{comment["avatarUrl"]}", {alt:comment["username"], :height => 60, :width => 60} %>
		<% end %>
		</div>
		<div class="left comment_cont">
			<p class="username">
				<%= link_to user_path(:user => comment["userId"], :username => comment["username"]) do %>
					<%= comment["username"] %>
				<% end %>
			</p>
			<p class="comment">
				<%= comment["comment"] %>
			</p>
		</div>
	</li>
<% end %>
<% if metas["data"]["nextPage"] != nil %>
	<%= link_to metas_more_path(:type => "comments", :post => post, :page => metas["data"]["nextPage"]), :class => 'btn btn-primary search_more_metas' do %>
		<i class="icon-plus"></i>&nbsp;&nbsp;&nbsp;More comments
	<% end %>
<% end %>

app/views/partials/_feed_items.html.erb
<% feeds["data"]["records"].each.with_index do |feed, index| %>
	<li>
		<div class="well user_infos">
			<%= image_tag "#{feed["avatarUrl"]}", {alt:feed["username"], :height => 30, :width => 30} %>
			<%= link_to feed["username"], user_path(:user => feed["userId"], :username => feed["username"]), :class => "username" %>
			<a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= feed["shareUrl"] %>" data-via="" data-lang="en" data-text="<%= feed["username"] %>'s post on Vine" data-related="" data-count="horizontal">Tweet</a>
		</div>
		<div class="feed_infos">
			<div class="feed_thumbnail left">
				<% if feed["postId"] %>
					<%= link_to post_path(:username => feed["username"], :post => feed["postId"]), :class => 'open-video-popup' do %>
						<%= image_tag "#{feed["thumbnailUrl"]}", {alt:feed["postId"], :height => 110, :width => 110} %>
					<% end %>
				<% end %>
			</div>
			<div class="description_cont left span10">
				<% if check_description_exists(feed["description"]) %>
					<h2>
						<%= link_to feed["description"], post_path(:username => feed["username"], :post => feed["postId"]), :class => 'open-video-popup-alt' %>
					</h2>
				<% end %>
				<p>
					<% if check_from_exists(feed["location"]) %>
						<i>from <%= feed["location"] %>,</i>
					<% end %>
					<i><%= format_date(feed["created"]) %> ago</i>
				</p>
			</div>
			<div class="clear"></div>
			<div class="feed_metas">
				<p class="post_metas_cont left">
					<% if feed["comments"] %>
						<span class="post_metas">
							<strong><%= format_large_number(feed["comments"]["count"]) %></strong> <i class="icon-comments-alt"></i>
						</span>
					<% end %>
					<% if feed["likes"] %>
						<span class="post_metas">
							<strong><%= format_large_number(feed["likes"]["count"]) %></strong> <i class="icon-heart-empty"></i>
						</span>
					<% end %>
				</p>
				<p class="feed_tags_cont left span10">
					<% feed["entities"].each.with_index do |entity, index| %>
						<% if entity["type"] == "tag" %>
							<% active = params[:tag] && params[:tag] == entity["title"] ? 'current' : '' %>
							<%= link_to "#"+entity["title"], tag_path(:tag => entity["title"]), :class => "tag btn btn-small "+ active %>
						<% end %>
					<% end %>
				</p>
				<div class="clear"></div>
			</div>
		</div>
	</li>
<% end %>

app/views/partials/_footer.html.erb
<footer class="navbar-fixed-bottom">
	<div id="credits">
		<div id="credits_container" class="container">
			<ul class="right credits_links">
				<li>
					<%= link_to "About", about_path %>
				</li> | 
				<li>
					<%= link_to "Contact", contact_path %>
				</li> | 
				<li>
					<%= link_to "What's new?", whatsnew_path %>
				</li>
			</ul>
			<div class="clear"></div>
		</div>
	</div>
</footer>

app/views/partials/_index_bubble.html.erb
<% @feed["data"]["records"].each.with_index do |feed, index| %>
	<%= link_to user_path(:user => feed["userId"], :username => feed["username"]), :class => "username" do %>
		<div class="marker">
			<span class="triangle">▲</span>
		</div>
	<% end %>
	<%= image_tag "#{feed["avatarUrl"]}", {alt:feed["username"], :height => 100, :width => 100} %>
<% end %>

app/views/partials/_likes.html.erb
<div class="white-popup">
	<% if @metas["success"] != false %>
		<ul class="metas_list likes_list">
			<%= render :partial => "partials/"+params[:type]+"_items", :locals => {:metas => @metas} %>	
		</ul>
	<% end %>
	<div class="clear"></div>
	<div class="loader"></div>
</div>

app/views/partials/_likes_items.html.erb
<% metas["data"]["records"].each.with_index do |like, index| %>
	<li class="left well">
		<%= link_to user_path(:user => like["userId"], :username => like["username"]) do %>
			<span><%= like["username"] %></span>
			<%= image_tag "#{like["avatarUrl"]}", {alt:like["username"], :height => 90, :width => 90} %>
		<% end %>
	</li>
<% end %>
<% if metas["data"]["nextPage"] != nil %>
	<%= link_to metas_more_path(:type => "likes", :post => post, :page => metas["data"]["nextPage"]), :class => 'btn btn-primary search_more_metas' do %>
		<i class="icon-plus"></i>&nbsp;&nbsp;&nbsp;More likes
	<% end %>
<% end %>

app/views/partials/_metas.html.erb
<% 

	prepare_title = ""
	prepare_description = "";
	prepare_keywords = "citivine, vine";

	case params["action"]
		when "list"
			if params["type"]
				case params["type"]
				when "promoted"
					prepare_title += "Promoted Vines"
					prepare_keywords += ", promoted"
				when "popular"
					prepare_title += "Popular Vines"
					prepare_keywords += ", popular"
				when "channels"
					prepare_title += "Channel "+params[:id]
					prepare_keywords += ", channel"
			end
		end
		when "post"
			prepare_title += params[:username]+"'s post"
			prepare_keywords += ", "+params[:username]
		when "tag"
			prepare_title += "Tag "+params[:tag]
			prepare_keywords += ", tag, "+params[:tag]
		when "user"
			prepare_title += params["username"]+"'s Vines"
			prepare_keywords += ", user, "+params["username"]
		when "search"
			prepare_title += "Search "+params["request"]
			prepare_keywords += ", search, "+params["request"]
		when "about"
			prepare_title += "About"
			prepare_keywords += ", about"
		when "contact"
			prepare_title += "Contact"
			prepare_keywords += ", contact"
		when "whatsnew"
			prepare_title += "What's new"
			prepare_keywords += ", whats new"
	end

	title prepare_title
	description prepare_description
	keywords prepare_keywords

%>

app/views/partials/_nav.html.erb
<%= nav_bar :fixed => :top, :brand => "citivine.co", :responsive => true do %>
    <%= menu_group do %>
        <%= menu_item "Popular", list_path(:type => :popular) %>
        <%= menu_item "Promoted", list_path(:type => :promoted) %>
        <%= drop_down "Channels" do %>
            <% @channels["data"]["records"].each.with_index do |channel, index| %>
                <%= menu_item list_path(:type => :channels, :id => channel["channelId"], :subtype => "recent") do %>
                    <%= image_tag "//d3422saexnbpnl.cloudfront.net"+channel["iconUrl"], {alt:"", :height => 20, :width => 20} %> 
                    <%= channel["channel"] %>
                <% end %>
            <% end %>
        <% end %>
        <%= drop_down "Tags" do %>
            <% @trending_tags["data"]["records"].each.with_index do |tag, index| %>
                <% if index < 8 %>
                    <%= menu_item "#"+tag["tag"], tag_path(:tag => tag["tag"]) %>
                <% end %>
            <% end %>
        <% end %>
    <% end %>
    <%= menu_group :pull => :right do %>
        <%= menu_item do %>
            <i class="display_settings icon-cog"></i> 
        <% end %>
        <li>
            <ul id="settings_dropdown" class="dropdown-menu" style="display:none">
                <li class="content">Number of items per page :</li>
                <li class="content page">
                    <% Citivine::Application::config.vine_count_items_options.each.with_index do |count, index| %>
                        <% active_class = session[:size].to_i == count.to_i ? 'disabled' : '' %>
                        <%= link_to count, change_session_size_path(:size => count), :class => active_class+' btn btn-primary btn-small set_size' %>
                    <% end %>
                </li>
                <li class="divider"></li>
                <li class="content page">
                    <label class="checkbox">
                        <% is_checked = session[:autoload] == '1' ? 'checked' : '' %>
                        <input type="checkbox" <%= is_checked %> class="set_autoload" value="true">
                    Automatically load next page
                    </label>
                </li>
                <li class="divider"></li>
                <li class="content page">
                    <label class="checkbox">
                        <% is_checked = session[:autoplay] == '1' ? 'checked' : '' %>
                        <input type="checkbox" <%= is_checked %> class="set_autoplay" value="true">
                    Autoplay videos
                    </label>
                </li>
                <li class="divider"></li>
                <li class="content">Volume : <span id="amount"><%= session[:volume] %></span></li>
                <li class="content page">
                    <div id="slider"></div>
                </li>
            </ul>
        </li>
    <% end %>
    <%= menu_group :pull => :right do %>
    	<%= form_tag({:controller => "feeds", :action => "search"}, :method => "get", :class => "navbar-form") do %>
	  		<%= text_field_tag :request, nil, placeholder: "Search people or tag!" %>
		<% end %>
    <% end %>
<% end %>
<script type="text/javascript">
    var autoload = <%= session[:autoload] %>;
    var autoplay = <%= session[:autoplay] %>;
    var volume = <%= session[:volume] %>/10;
</script>

app/views/partials/_pagination.html.erb
<ul class="left pagination">
	<% disabled = previous_page == nil ? "disabled" : "" %>
	<% link = disabled == 'disabled' ? "#" : params.merge(:page => previous_page) %>
	<li class="previous <%= disabled %>">
		<%= link_to link, :class => disabled+' btn btn-primary' do %>
			<i class="icon-caret-left"></i>&nbsp;&nbsp;&nbsp;Newer
		<% end %>
	</li>
</ul>
<ul class="right pagination">
	<% disabled = next_page == nil ? "disabled" : "" %>
	<% link = disabled == 'disabled' ? "#" : params.merge(:page => next_page) %>
	<li class="next">
		<%= link_to link, :class => disabled+' btn btn-primary' do %>
			Older&nbsp;&nbsp;&nbsp;<i class="icon-caret-right"></i>
		<% end %>
	</li>
</ul>
<div class="clear"></div>

app/views/partials/_post.html.erb
<div id="video_cont_" class="white-popup">
	<video width="320" height="320" class="" poster="" loop="" preload="metadata" poster="">
		<source src="<%= @videoUrl %>" type="video/mp4">
	</video>
</div>

app/views/partials/_post_popup.html.erb
<div id="video_cont" class="video_cont white-popup clearfix">
	<% @post["data"]["records"].each.with_index do |post, index| %>
		<div id="post_cont" class="left">
			<h2>
				<%= auto_tag_vine(post["description"]).html_safe %>	
			</h2>
			<p>
				<% if check_from_exists(post["location"]) %>
					<i>from <%= post["location"] %>,</i>
				<% end %>
				<i><%= format_date(post["created"]) %> ago</i>
			</p>
			<% volume_class = session[:volume] == '0' ? 'off' : 'on' %>
			<a href="#" class="mute-button <%= volume_class %>"></a>
			<video id="video_<%= post["postId"] %>" class="video-js" poster="<%= post["thumbnailUrl"] %>" loop="" preload="false">
				<source src="<%= post["videoUrl"] %>" type="video/mp4">
			</video>
		</div>
		<div id="metas_cont" class="left">
			<div class="well user_infos clearfix">
				<%= link_to user_path(:user => post["userId"], :username => post["username"]), :class => "username" do %>
					<%= image_tag "#{post["avatarUrl"]}", {alt:post["username"], :height => 100, :width => 100, :class => "left user_avatar"} %>
				<% end %>
				<h3 class="left">
					<%= link_to post["username"], user_path(:user => post["userId"], :username => post["username"]), :class => "username" %>
				</h3>
				<span class="left">
					<%= @feeds["data"]["count"] %> vine<%= @feeds["data"]["count"] == 1 ? '' : 's' %>
				</span>
			</div>
			<ul class="nav nav-tabs">
				<li class="active share">
					<%= link_to "Share", '' %>
				</li>
				<% if @comments["data"]["count"].to_i > 0 %>
			        <li class="comments">
			        	<%= link_to format_large_number(@comments["data"]["count"])+" Comments", '' %>
			        </li>
		        <% end %>
		        <% if @likes["data"]["count"].to_i > 0 %>
			        <li class="likes">
			        	<%= link_to format_large_number(@likes["data"]["count"])+" Likes", '' %>
			        </li>
		        <% end %>
	      	</ul>
	      	<ul id="share" class="metas">
	      		<a target="_blank" onclick="return !window.open(this.href, 'Twitter', 'width=700,height=400')" href="https://twitter.com/share?url=<%= post["shareUrl"] %>&amp;text=<%= post["description"] %>">
	      			<i class="icon-share icon-twitter"></i>
	    		</a>
      			<a target="_blank" onclick="return !window.open(this.href, 'Facebook', 'width=700,height=400')" href="https://www.facebook.com/sharer/sharer.php?u=<%= post["shareUrl"] %>">
	      			<i class="icon-share icon-facebook"></i>
	    		</a>
	      		<h3>Video URL:</h3>
				<input value="<%= url_for(:only_path => false) %>" name="video-url">
				<div id="tags">
					<% if post["entities"].length > 0 %>
						<h3>Tags:</h3>
					<% end %>
	    			<% post["entities"].each.with_index do |entity, index| %>
						<% if entity["type"] == "tag" %>
							<% active = params[:tag] && params[:tag] == entity["title"] ? 'current' : '' %>
							<%= link_to entity["title"], tag_path(:tag => entity["title"]), :class => "tag btn btn-small "+ active %>
						<% end %>
					<% end %>
				</div>
			</ul>
			<% if @comments["data"]["count"].to_i > 0 %>
				<ul id="comments" class="metas">
					<%= render :partial => 'partials/comments_items', :locals => {:metas => @comments, :post => params[:post]} %>
				</ul>
			<% end %>
			<% if @likes["data"]["count"].to_i > 0 %>
				<ul id="likes" class="metas clearfix likes_list">
					<%= render :partial => 'partials/likes_items', :locals => {:metas => @likes, :post => params[:post]} %>
				</ul>
			<% end %>
		</div>
	<% end %>
</div>

app/views/partials/_search_users.html.erb
<% users["data"]["records"].each.with_index do |user, index| %>
	<% active = params[:request] == user["username"].downcase ? 'current' : ''; %>
	<li class="left well <%= active %>">
		<%= link_to user_path(:user => user["userId"], :username => user["username"]), :class => "username" do %>
			<span><%= user["username"] %></span>
			<%= image_tag "#{user["avatarUrl"]}", {alt:user["username"], :height => 100, :width => 100} %>
		<% end %>
	</li>
<% end %>

app/views/partials/_single_page_sidebar.html.erb
<ul id="contact_sidebar" class="right">
	<% about_active_class = active == 'about' ? 'active' : ''; %>
	<li class="<%= about_active_class %>">
		<%= link_to about_path do %>
			<i class="icon-chevron-right"></i>About
		<% end %>
	</li>
	<hr/>
	<% contact_active_class = active == 'contact' ? 'active' : ''; %>
	<li class="<%= contact_active_class %>">
		<%= link_to contact_path  do %>
			<i class="icon-chevron-right"></i>Contact
		<% end %>
	</li>
	<hr/>
	<% whatsnew_active_class = active == 'whatsnew' ? 'active' : ''; %>
	<li class="<%= whatsnew_active_class %>">
		<%= link_to whatsnew_path  do %>
			<i class="icon-chevron-right"></i>What's new?
		<% end %>
	</li>
</ul>