config/routes.rb
Citivine::Application.routes.draw do
	  get "index/index"
	  root :to => "index#index"
	  #match for for webrick subdirectory
	  match '/citivine' => 'index#index'
	  #Search
	  match '/item(/:item)' => 'index#index', :as => :index_item
	  #get feeds (by type, subtype (channels), id (channels))
	  match 'list/:type(/:subtype)(/id/:id)(/page/:page)(/load/:load)' => 'feeds#list', :as => :list
	  #Search
	  match 'search(/:request)(/:type)(/:page)' => 'feeds#search', :as => :search
	  #list feeds by tag id
	  match 'tag/:tag(/page/:page)(/load/:load)(/count/:size)' => 'feeds#tag', :as => :tag
	  #fetch metas by post
	  match 'post(/cat/:cat)(/:type)/:post' => 'feeds#metas', :as => :metas
	  #fetch more metas by post
	  match 'post(/cat/:cat)(/:type)/:post(/page/:page)' => 'feeds#metas_more', :as => :metas_more
	  #uniq user
	  match 'user/:user(/:username)(/page/:page)(/load/:load)' => 'feeds#user', :as => :user
	  #uniq vine uniq post / video
	  match 'vine/:username/:post' => 'feeds#post', :as => :post
	  #test route
	  match 'test/test' => 'feeds#test', :as => :test
	  #Set number of items per page
	  match 'count/:size' => 'index#change_session_size', :as => :change_session_size
	  #Set autoload
	  match 'autoload/:autoload' => 'index#change_session_autoload', :as => :change_session_autoload
	  #Set autoplay
	  match 'autoplay/:autoplay' => 'index#change_session_autoplay', :as => :change_session_autoplay
	  #Set volume
	  match 'volume/:volume' => 'index#change_session_volume', :as => :change_session_volume
	  #About page
	  match 'whatsnew' => 'index#whatsnew', :as => :whatsnew
	  #About page
	  match 'about' => 'index#about', :as => :about
	  #Contact page
	  match 'contact' => 'index#contact', :as => :contact, :via => :get
	  match 'contact' => 'index#contact_send', :as => :contact_send, :via => :post
end

app/views/index/about.html.erb
<%= render :partial => "partials/metas", :locals => { :params => params } %>
<%= render :partial => "partials/single_page_sidebar", :locals => {:active => "about"} %>
<h2>About</h2>
<hr class="single_page span7"/>
<div class="single_page left about_content span7">
	<p>The source code is available on <%= link_to "GitHub", "//github.com/guillaumer/citivine",:target => "blank" %>.</p>
	<h3>How it works?</h3>
	<p>Citivine gathers all feeds in real-time from the (non-official) Vine API, also used in the (offcial) iPhone and Android app. You may find some detailed informations on how the API works on various blogs and GitHub repos, such as:</p>
	<ul>
		<li><%= link_to "http://khakimov.com/blog/2013/03/12/vines-undocumented-api/", "http://khakimov.com/blog/2013/03/12/vines-undocumented-api/",:target => "blank" %></li>
		<li><%= link_to "https://github.com/starlock/vino/wiki/API-Reference", "https://github.com/starlock/vino/wiki/API-Reference", :target => "blank" %></li>
		<li><%= link_to "https://github.com/search?q=api.vineapp.com&type=Code", "https://github.com/search?q=api.vineapp.com&type=Code", :target => "blank" %></li>
	</ul>
	<p>However, some of these infos are deprecated as Vine is rapidly evolving. In addition to the provided links, here is what I'm also using for pulling datas:</p>
	<ul>
		<li>
			<%= link_to "https://vine.co/explore", "https://vine.co/explore", :target => "blank" %> and the newly added <%= link_to "https://vine.co/explore/v2", "https://vine.co/explore/v2", :target => "blank" %> are the webpages shown in the <i>Explore</i> section of the mobile app.
		</li>
		<li>
			https://api.vineapp.com/timelines/posts/post_id is the endpoint for retrieving a single post (recently added, yay!).
		</li>
		<li>
			<i>https://api.vineapp.com/posts/post_id/comments</i> and <i>https://api.vineapp.com/posts/post_id/likes</i> for respectively getting the comments and likes associated to a Vine video (post).
		</li>
		<li>
			The <i>page</i> and <i>size</i> parameters can be appended to every API URLs, although I wouldn't advise setting the <i>size</i> too high for obvious load issues.
		</li>
	</ul>
	<h3>Disclaimer</h3>
	<p>Citivine is in no way affiliated or related to Vine (<%= link_to "Vine Labs, Inc", "https://vine.co/", :target => "blank" %>) nor Twitter. All data and informations displayed on this site fall under the Vine privacy policy and terms of service. Content is also not moderated, although Vine has lately been working hard on this. Some is still not appropriated and should not be viewed by younglings.</p>
	<h3>I want to delete my profile</h3>
	<p>All the informations displayed here are issued from the Vine mobile application. You should then consider deleting your account by contacting <%= link_to "Vine", "http://www.vineapp.com/contact", :target => "blank" %>.</p>
	<h3>Suggestions</h3>
	<p>Feel free to <%= link_to "contact me", contact_path() %> if you have any questions, suggestions or technical information to provide.</p>
</div>
<div class="clear"></div>

app/views/index/contact.html.erb
<%= render :partial => "partials/metas", :locals => { :params => params } %>
<%= render :partial => "partials/single_page_sidebar", :locals => {:active => "contact"} %>
<h2>Contact</h2>
<hr class="single_page span7"/>
<div class="single_page left contact_content">
	<h3>Direct message</h3>
	<% if flash[:alert] %>
		<div class="alert alert-error">
        	<strong>Error:</strong> <%= flash[:alert] %>
      	</div>
	<% end %>
	<% if notice %>
		<div class="alert alert-success">
        	<%= notice %>
      	</div>
	<% end %>
	<%= form_for @message, :url => contact_send_path, method: "post", id: "contact_form" do |form| %>
	  <%= form.label :email, "Email" %>
	  <%= form.text_field :email %>
	  <%= form.submit "Send!", :class => 'btn btn-success' %>
	  <%= form.label :body, "Message" %>
	  <%= form.text_area :body %>
	<% end %>
</div>
<div class="clear"></div>

app/views/index/index.html.erb
<div id="homepage_background">
	<div id="header">
	</div>
	<div id="last_popular_cont">
		<div id="last_popular" class="container">
			<h1>Last popular vines</h1>
			<div id="owl-demo" class="owl-carousel owl-theme">
				<% @feeds["data"]["records"].each.with_index do |feed, index| %>
					<div class="item">
						<%= image_tag "#{feed["thumbnailUrl"]}", {alt:feed["username"], :height => 300, :width => 300, :class => "popular_video"} %>
						<% volume_class = session[:volume] == '0' ? 'off' : 'on' %>
						<a href="#" class="mute-button <%= volume_class %>"></a>
						<video id="video_<%= feed["postId"] %>" class="video-js" poster="<%= feed["thumbnailUrl"] %>" loop="" preload="false">
							<source src="<%= feed["videoUrl"] %>" type="video/mp4">
						</video>
						<%= link_to user_path(:user => feed["userId"], :username => feed["username"]) do %>
							<p class="user clearfix">
								<%= image_tag "#{feed["avatarUrl"]}", {alt:feed["username"], :height => 78, :width => 78} %>
								<span class="post_username">
									<span class="username"><%= feed["username"] %></span>
									<span class="post_count"><%= feed["post_count"] %> vine<%= feed["post_count"].to_i == 1 ? '' : 's' %></span>
								</span>
							</p>
						<% end %>
						<%= link_to post_path(:username => feed["username"], :post => feed["postId"]), :class => "hyperlink" do %>
							See this vine<i class="right fa icon-external-link"></i>
						<% end %>
					</div>
				<% end %>
			</div>
			<div class="customNavigation clearfix">
			  <a class="btn prev">Previous</a>
			  <a class="btn next">Next</a>
			</div>
		</div>
	</div>
	<div id="metas" class="container">
		<div class="span4">
			<h1>Tags</h1>
			<% @trending_tags["data"]["records"].each.with_index do |tag, index| %>
				<%= link_to "#"+tag["tag"], tag_path(:tag => tag["tag"]), :class => "tag btn btn-small" %>
	        <% end %>
		</div>
		<div class="span4">
			<h1>Channels</h1>
			<% @channels["data"]["records"].each.with_index do |channel, index| %>
                <%= link_to list_path(:type => :channels, :id => channel["channelId"], :subtype => "recent"), :class => "tag btn btn-small" do %>
                    <%= image_tag "//d3422saexnbpnl.cloudfront.net"+channel["iconUrl"], {alt:"", :height => 20, :width => 20} %> 
                    <%= channel["channel"] %>
                <% end %>
            <% end %>
		</div>
		<div class="span4">
			<h1>#vine</h1>
			<a height="400" class="twitter-timeline" href="https://twitter.com/search?q=%23vine" data-widget-id="410179885198344192"></a>
		</div>
	</div>
</div>
<style type="text/css">
	body {
		padding-top: 0;
	}
	body .navbar, body .navbar-inner {
		background: transparent;
	}
	.dropdown-menu>li>a {
		color: #2FA4E7 !important;
	}
</style>

app/views/index/whatsnew.html.erb
<%= render :partial => "partials/metas", :locals => { :params => params } %>
<%= render :partial => "partials/single_page_sidebar", :locals => {:active => "whatsnew"} %>
<h2>Whats New?</h2>
<hr class="single_page span7"/>
<div class="single_page left about_content span7">
	<h3>Planned</h3>
	<ul>
		<li>User credentials</li>
		<li>User actions (like, etc.)</li>
		<li>Vine Geolocation</li>
	</ul>
	<h3>v1.1</h3>
	<ul>
		<li>Permalink</li>
		<li>User actions (share, etc.)</li>
	</ul>
	<h3>v1.0</h3>
	<ul>
		<li>Vine exploring (promoted and populars feeds)</li>
		<li>Popular tags and current channels</li>
		<li>User profile</li>
		<li>Search</li>
	</ul>
</div>
<div class="clear"></div>